/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiElements;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import objectOriented.Dijkstra;
import objectOriented.Vertex;

/**
 *
 * @author Joshua
 */
public class SimpleDGUI extends javax.swing.JFrame {

    Dijkstra dAlg;
    /**
     * Creates new form SimpleDGUI
     */
    public SimpleDGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Button_Browse = new javax.swing.JButton();
        ComboBox_FilePath = new javax.swing.JComboBox();
        Button_LoadMatrix = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_MinPath = new javax.swing.JTextArea();
        Label_Source = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Label_Target = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Label_MinDis = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 420));
        setMinimumSize(new java.awt.Dimension(450, 420));

        jLabel1.setText("File Location");

        Button_Browse.setText("Browse");
        Button_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BrowseActionPerformed(evt);
            }
        });

        ComboBox_FilePath.setEditable(true);

        Button_LoadMatrix.setText("Load Matrix");
        Button_LoadMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoadMatrixActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Step 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Step 2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Step 3");

        jLabel5.setText("The minimum distance from vertex");

        TextArea_MinPath.setBackground(new java.awt.Color(240, 240, 240));
        TextArea_MinPath.setColumns(20);
        TextArea_MinPath.setRows(5);
        jScrollPane1.setViewportView(TextArea_MinPath);

        Label_Source.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Source.setText("v0");

        jLabel6.setText("to");

        Label_Target.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Target.setText("--");

        jLabel7.setText("is:");

        Label_MinDis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label_MinDis.setForeground(new java.awt.Color(0, 0, 255));
        Label_MinDis.setText("--");

        jLabel8.setText("The minimum path is:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBox_FilePath, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Browse))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_LoadMatrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_Source)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_Target)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_MinDis)))
                                .addGap(0, 125, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Browse)
                    .addComponent(ComboBox_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_LoadMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(Label_Source)
                    .addComponent(jLabel6)
                    .addComponent(Label_Target)
                    .addComponent(jLabel7)
                    .addComponent(Label_MinDis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        
        int returnVal = fc.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            ComboBox_FilePath.addItem(file.getPath());
            ComboBox_FilePath.setSelectedIndex(ComboBox_FilePath.getItemCount()-1);
        }
        
    }//GEN-LAST:event_Button_BrowseActionPerformed

    private void Button_LoadMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoadMatrixActionPerformed
        try 
        {
            switch (ComboBox_FilePath.getSelectedItem().toString())
            {
                case "9 Vertices Directed": dAlg = new Dijkstra(Dijkstra.NineDirectedPath); break;
                case "25 Vertices Undirected": dAlg = new Dijkstra(Dijkstra.TwentyFiveDirectedPath); break;
                case "100 Vertices Directed": dAlg = new Dijkstra(Dijkstra.HundredDirectedPath); break;
                case "100 Vertices Undirected": dAlg = new Dijkstra(Dijkstra.HundredUnDirectedPath); break;
                default: dAlg = new Dijkstra(ComboBox_FilePath.getSelectedItem().toString());
            }
        }
        catch (IOException ex) 
        {
            Logger.getLogger(SimpleDGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dAlg.computePaths(dAlg.getSourceVertex());
        Label_Target.setText(dAlg.getLastVertex().toString());
        Label_MinDis.setText(Double.toString(dAlg.getLastVertex().getMinDistance()));
        TextArea_MinPath.setText("");
        for(Vertex v: dAlg.getShortestPathTo(dAlg.getLastVertex()))
            TextArea_MinPath.append(v.toString()+"\n");
    
    }//GEN-LAST:event_Button_LoadMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleDGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Browse;
    private javax.swing.JButton Button_LoadMatrix;
    private javax.swing.JComboBox ComboBox_FilePath;
    private javax.swing.JLabel Label_MinDis;
    private javax.swing.JLabel Label_Source;
    private javax.swing.JLabel Label_Target;
    private javax.swing.JTextArea TextArea_MinPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
